name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  XCODE_WORKSPACE: "DevelopersButler.xcodeproj"
  XCODE_SCHEME: "DevelopersButler"
  CODE_SIGN_IDENTITY: "-"
  BUILD_DIR: "build"
  XCODE_ARCHIVE: "DevelopersButler.xcarchive"
  APP_NAME: "DevelopersButler.app"
  EXPORT_OPTIONS_PLIST: "exportOptions.plist"
  DMG_NAME: "DevelopersButler"
  DMG_FILE_NAME: "DevelopersButler.dmg"

jobs:
  build:
    runs-on: macos-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Build
      run: xcodebuild -workspace "$XCODE_WORKSPACE" -scheme "$XCODE_SCHEME" archive CODE_SIGN_IDENTITY="$CODE_SIGN_IDENTITY" -archivePath "$BUILD_DIR/$XCODE_ARCHIVE"
    - name: Export
      run: |
        plutil -convert xml1 - -o "$EXPORT_OPTIONS_PLIST" << EOF
          {
            "destination": "export",
            "method": "mac-application"
          }
        EOF
        xcodebuild -exportArchive -archivePath "$BUILD_DIR/$XCODE_ARCHIVE" -exportPath "$BUILD_DIR" -exportOptionsPlist "$EXPORT_OPTIONS_PLIST"
    - name: Resign App
      run: codesign --force --deep -s "$CODE_SIGN_IDENTITY" "$BUILD_DIR/$APP_NAME"
    - name: Make DMG
      run: hdiutil create -srcdir "$BUILD_DIR" -volname "$DMG_NAME" "$DMG_FILE_NAME"
    - name: Upload
      uses: actions/upload-artifact@v3
      with:
        name: Build
        path: ${{ env.DMG_FILE_NAME }}
